
package edu.nju.student.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticationService", targetNamespace = "http://jw.nju.edu.cn/wsdl", wsdlLocation = "file:/D:/semester3_3/soa/assignment/assignment10/sourceCode/StudentService/src/main/resources/wsdl/StudentAuth.wsdl")
public class AuthenticationService_Service
    extends Service
{

    private final static URL AUTHENTICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONSERVICE_EXCEPTION;
    private final static QName AUTHENTICATIONSERVICE_QNAME = new QName("http://jw.nju.edu.cn/wsdl", "AuthenticationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/semester3_3/soa/assignment/assignment10/sourceCode/StudentService/src/main/resources/wsdl/StudentAuth.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONSERVICE_WSDL_LOCATION = url;
        AUTHENTICATIONSERVICE_EXCEPTION = e;
    }

    public AuthenticationService_Service() {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICE_QNAME);
    }

    public AuthenticationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICE_QNAME, features);
    }

    public AuthenticationService_Service(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONSERVICE_QNAME);
    }

    public AuthenticationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONSERVICE_QNAME, features);
    }

    public AuthenticationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticationService
     */
    @WebEndpoint(name = "AuthenticationServiceImplPort")
    public AuthenticationService getAuthenticationServiceImplPort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "AuthenticationServiceImplPort"), AuthenticationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationService
     */
    @WebEndpoint(name = "AuthenticationServiceImplPort")
    public AuthenticationService getAuthenticationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "AuthenticationServiceImplPort"), AuthenticationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONSERVICE_EXCEPTION!= null) {
            throw AUTHENTICATIONSERVICE_EXCEPTION;
        }
        return AUTHENTICATIONSERVICE_WSDL_LOCATION;
    }

}
