
package edu.nju.student.service;

import edu.nju.student.exception.ErrorPassword;
import edu.nju.student.exception.InvalidStudentId;
import edu.nju.student.model.学生信息;
import edu.nju.student.model.账号类型;
import edu.nju.student.utils.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationService", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationService {


    /**
     * 登录操作
     * 
     * @param parameters
     * @return
     *     returns edu.nju.student.controller.学生信息
     * @throws ErrorPassword
     * @throws InvalidStudentId
     */
    @WebMethod
    @WebResult(name = "\u5b66\u751f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 学生信息 login(
        @WebParam(name = "\u8d26\u53f7", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
                账号类型 parameters)
        throws ErrorPassword, InvalidStudentId
    ;

}
