
package edu.nju.student.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScoreManageService", targetNamespace = "http://jw.nju.edu.cn/wsdl", wsdlLocation = "file:/D:/semester3_3/soa/assignment/assignment10/sourceCode/StudentService/src/main/resources/wsdl/ScoreManage.wsdl")
public class ScoreManageService_Service
    extends Service
{

    private final static URL SCOREMANAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCOREMANAGESERVICE_EXCEPTION;
    private final static QName SCOREMANAGESERVICE_QNAME = new QName("http://jw.nju.edu.cn/wsdl", "ScoreManageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/semester3_3/soa/assignment/assignment10/sourceCode/StudentService/src/main/resources/wsdl/ScoreManage.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCOREMANAGESERVICE_WSDL_LOCATION = url;
        SCOREMANAGESERVICE_EXCEPTION = e;
    }

    public ScoreManageService_Service() {
        super(__getWsdlLocation(), SCOREMANAGESERVICE_QNAME);
    }

    public ScoreManageService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCOREMANAGESERVICE_QNAME, features);
    }

    public ScoreManageService_Service(URL wsdlLocation) {
        super(wsdlLocation, SCOREMANAGESERVICE_QNAME);
    }

    public ScoreManageService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCOREMANAGESERVICE_QNAME, features);
    }

    public ScoreManageService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreManageService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScoreManageService
     */
    @WebEndpoint(name = "ScoreManageServiceImplPort")
    public ScoreManageService getScoreManageServiceImplPort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "ScoreManageServiceImplPort"), ScoreManageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoreManageService
     */
    @WebEndpoint(name = "ScoreManageServiceImplPort")
    public ScoreManageService getScoreManageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "ScoreManageServiceImplPort"), ScoreManageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCOREMANAGESERVICE_EXCEPTION!= null) {
            throw SCOREMANAGESERVICE_EXCEPTION;
        }
        return SCOREMANAGESERVICE_WSDL_LOCATION;
    }

}
