
package edu.nju.student.service;

import edu.nju.student.exception.InvalidCourseId;
import edu.nju.student.exception.InvalidScore;
import edu.nju.student.exception.InvalidStudentId;
import edu.nju.student.model.学号课程号类型;
import edu.nju.student.model.课程成绩列表类型;
import edu.nju.student.model.课程成绩类型;
import edu.nju.student.utils.ObjectFactory;
import edu.nju.student.my_enum.排序方式类型;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoreManageService", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScoreManageService {


    /**
     * 成绩查询操作
     * 
     * @param parameters
     * @return
     *     returns edu.nju.student.model.课程成绩列表类型
     * @throws InvalidStudentId
     */
    @WebMethod
    @WebResult(name = "\u8bfe\u7a0b\u6210\u7ee9\u5217\u8868", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 queryGrade(
        @WebParam(name = "\u5b66\u53f7", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
        String parameters)
        throws InvalidStudentId
    ;

    /**
     * 成绩修改操作
     * 
     * @param parameters
     * @return
     *     returns edu.nju.student.model.课程成绩列表类型
     * @throws InvalidStudentId
     * @throws InvalidCourseId
     * @throws InvalidScore
     */
    @WebMethod
    @WebResult(name = "\u8bfe\u7a0b\u6210\u7ee9\u5217\u8868", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 modifyGrade(
        @WebParam(name = "\u8bfe\u7a0b\u6210\u7ee9", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
                课程成绩类型 parameters)
        throws InvalidCourseId, InvalidScore, InvalidStudentId
    ;

    /**
     * 成绩新增操作
     * 
     * @param parameters
     * @throws InvalidStudentId
     * @throws InvalidCourseId
     * @throws InvalidScore
     */
    @WebMethod
    public void addGrade(
        @WebParam(name = "\u8bfe\u7a0b\u6210\u7ee9\u5217\u8868", targetNamespace = "http://jw.nju.edu.cn/schema", mode = WebParam.Mode.INOUT, partName = "parameters")
        Holder<课程成绩列表类型> parameters)
        throws InvalidCourseId, InvalidScore, InvalidStudentId
    ;

    /**
     * 成绩注销操作
     * 
     * @param parameters
     * @return
     *     returns edu.nju.student.model.课程成绩列表类型
     * @throws InvalidStudentId
     * @throws InvalidCourseId
     */
    @WebMethod
    @WebResult(name = "\u8bfe\u7a0b\u6210\u7ee9\u5217\u8868", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 deleteGrade(
        @WebParam(name = "\u5b66\u53f7\u8bfe\u7a0b\u53f7", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
                学号课程号类型 parameters)
        throws InvalidCourseId, InvalidStudentId
    ;

    /**
     * 成绩排序操作
     * 
     * @param parameters
     * @return
     *     returns edu.nju.student.model.课程成绩列表类型
     * @throws InvalidStudentId
     * @throws InvalidCourseId
     */
    @WebMethod
    @WebResult(name = "\u8bfe\u7a0b\u6210\u7ee9\u5217\u8868", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 sortGrade(
        @WebParam(name = "\u6392\u5e8f\u65b9\u5f0f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
                排序方式类型 parameters)
        throws InvalidCourseId, InvalidStudentId
    ;

}
